import * as React from 'react';
import './styles.css';

import { IconContext } from 'react-icons';
import {
  GoAlert,
  GoArchive,
  GoArrowBoth,
  GoArrowDown,
  GoArrowLeft,
  GoArrowRight,
  GoArrowSmallDown,
  GoArrowSmallLeft,
  GoArrowSmallRight,
  GoArrowSmallUp,
  GoArrowUp,
  GoBeaker,
  GoBell,
  GoBold,
  GoBook,
  GoBookmark,
  GoBriefcase,
  GoBroadcast,
  GoBrowser,
  GoBug,
  GoCalendar,
  GoCheck,
  GoChecklist,
  GoChevronDown,
  GoChevronLeft,
  GoChevronRight,
  GoChevronUp,
  GoCircleSlash,
  GoCircuitBoard,
  GoClippy,
  GoClock,
  GoCloudDownload,
  GoCloudUpload,
  GoCode,
  GoCommentDiscussion,
  GoComment,
  GoCreditCard,
  GoDash,
  GoDashboard,
  GoDatabase,
  GoDesktopDownload,
  GoDeviceCameraVideo,
  GoDeviceCamera,
  GoDeviceDesktop,
  GoDeviceMobile,
  GoDiffAdded,
  GoDiffIgnored,
  GoDiffModified,
  GoDiffRemoved,
  GoDiffRenamed,
  GoDiff,
  GoEllipsis,
  GoEyeClosed,
  GoEye,
  GoFileBinary,
  GoFileCode,
  GoFileDirectory,
  GoFileMedia,
  GoFilePdf,
  GoFileSubmodule,
  GoFileSymlinkDirectory,
  GoFileSymlinkFile,
  GoFileZip,
  GoFile,
  GoFlame,
  GoFoldDown,
  GoFoldUp,
  GoFold,
  GoGear,
  GoGift,
  GoGistSecret,
  GoGist,
  GoGitBranch,
  GoGitCommit,
  GoGitCompare,
  GoGitMerge,
  GoGitPullRequest,
  GoGithubAction,
  GoGlobe,
  GoGrabber,
  GoGraph,
  GoHeart,
  GoHistory,
  GoHome,
  GoHorizontalRule,
  GoHubot,
  GoInbox,
  GoInfo,
  GoIssueClosed,
  GoIssueOpened,
  GoIssueReopened,
  GoItalic,
  GoJersey,
  GoKebabHorizontal,
  GoKebabVertical,
  GoKey,
  GoKeyboard,
  GoLaw,
  GoLightBulb,
  GoLinkExternal,
  GoLink,
  GoListOrdered,
  GoListUnordered,
  GoLocation,
  GoLock,
  GoLogoGist,
  GoLogoGithub,
  GoMailRead,
  GoMail,
  GoMarkGithub,
  GoMarkdown,
  GoMegaphone,
  GoMention,
  GoMilestone,
  GoMirror,
  GoMortarBoard,
  GoMute,
  GoNoNewline,
  GoNote,
  GoOctoface,
  GoOrganization,
  GoPackage,
  GoPaintcan,
  GoPencil,
  GoPerson,
  GoPin,
  GoPlay,
  GoPlug,
  GoPlusSmall,
  GoPlus,
  GoPrimitiveDot,
  GoPrimitiveSquare,
  GoProject,
  GoPulse,
  GoQuestion,
  GoQuote,
  GoRadioTower,
  GoReply,
  GoRepoClone,
  GoRepoForcePush,
  GoRepoForked,
  GoRepoPull,
  GoRepoPush,
  GoRepo,
  GoReport,
  GoRequestChanges,
  GoRocket,
  GoRss,
  GoRuby,
  GoScreenFull,
  GoScreenNormal,
  GoSearch,
  GoServer,
  GoSettings,
  GoShield,
  GoSignIn,
  GoSignOut,
  GoSmiley,
  GoSquirrel,
  GoStar,
  GoStop,
  GoSync,
  GoTag,
  GoTasklist,
  GoTelescope,
  GoTerminal,
  GoTextSize,
  GoThreeBars,
  GoThumbsdown,
  GoThumbsup,
  GoTools,
  GoTrashcan,
  GoTriangleDown,
  GoTriangleLeft,
  GoTriangleRight,
  GoTriangleUp,
  GoUnfold,
  GoUnmute,
  GoUnverified,
  GoVerified,
  GoVersions,
  GoWatch,
  GoX,
  GoZap,
} from 'react-icons/go';

export const GithubIconType: { [key: string]: React.ElementType } = {
  'Go-Alert': GoAlert,
  'Go-Archive': GoArchive,
  'Go-ArrowBoth': GoArrowBoth,
  'Go-ArrowDown': GoArrowDown,
  'Go-ArrowLeft': GoArrowLeft,
  'Go-ArrowRight': GoArrowRight,
  'Go-ArrowSmallDown': GoArrowSmallDown,
  'Go-ArrowSmallLeft': GoArrowSmallLeft,
  'Go-ArrowSmallRight': GoArrowSmallRight,
  'Go-ArrowSmallUp': GoArrowSmallUp,
  'Go-ArrowUp': GoArrowUp,
  'Go-Beaker': GoBeaker,
  'Go-Bell': GoBell,
  'Go-Bold': GoBold,
  'Go-Book': GoBook,
  'Go-Bookmark': GoBookmark,
  'Go-Briefcase': GoBriefcase,
  'Go-Broadcast': GoBroadcast,
  'Go-Browser': GoBrowser,
  'Go-Bug': GoBug,
  'Go-Calendar': GoCalendar,
  'Go-Check': GoCheck,
  'Go-Checklist': GoChecklist,
  'Go-ChevronDown': GoChevronDown,
  'Go-ChevronLeft': GoChevronLeft,
  'Go-ChevronRight': GoChevronRight,
  'Go-ChevronUp': GoChevronUp,
  'Go-CircleSlash': GoCircleSlash,
  'Go-CircuitBoard': GoCircuitBoard,
  'Go-Clippy': GoClippy,
  'Go-Clock': GoClock,
  'Go-CloudDownload': GoCloudDownload,
  'Go-CloudUpload': GoCloudUpload,
  'Go-Code': GoCode,
  'Go-CommentDiscussion': GoCommentDiscussion,
  'Go-Comment': GoComment,
  'Go-CreditCard': GoCreditCard,
  'Go-Dash': GoDash,
  'Go-Dashboard': GoDashboard,
  'Go-Database': GoDatabase,
  'Go-DesktopDownload': GoDesktopDownload,
  'Go-DeviceCameraVideo': GoDeviceCameraVideo,
  'Go-DeviceCamera': GoDeviceCamera,
  'Go-DeviceDesktop': GoDeviceDesktop,
  'Go-DeviceMobile': GoDeviceMobile,
  'Go-DiffAdded': GoDiffAdded,
  'Go-DiffIgnored': GoDiffIgnored,
  'Go-DiffModified': GoDiffModified,
  'Go-DiffRemoved': GoDiffRemoved,
  'Go-DiffRenamed': GoDiffRenamed,
  'Go-Diff': GoDiff,
  'Go-Ellipsis': GoEllipsis,
  'Go-EyeClosed': GoEyeClosed,
  'Go-Eye': GoEye,
  'Go-FileBinary': GoFileBinary,
  'Go-FileCode': GoFileCode,
  'Go-FileDirectory': GoFileDirectory,
  'Go-FileMedia': GoFileMedia,
  'Go-FilePdf': GoFilePdf,
  'Go-FileSubmodule': GoFileSubmodule,
  'Go-FileSymlinkDirectory': GoFileSymlinkDirectory,
  'Go-FileSymlinkFile': GoFileSymlinkFile,
  'Go-FileZip': GoFileZip,
  'Go-File': GoFile,
  'Go-Flame': GoFlame,
  'Go-FoldDown': GoFoldDown,
  'Go-FoldUp': GoFoldUp,
  'Go-Fold': GoFold,
  'Go-Gear': GoGear,
  'Go-Gift': GoGift,
  'Go-GistSecret': GoGistSecret,
  'Go-Gist': GoGist,
  'Go-GitBranch': GoGitBranch,
  'Go-GitCommit': GoGitCommit,
  'Go-GitCompare': GoGitCompare,
  'Go-GitMerge': GoGitMerge,
  'Go-GitPullRequest': GoGitPullRequest,
  'Go-GithubAction': GoGithubAction,
  'Go-Globe': GoGlobe,
  'Go-Grabber': GoGrabber,
  'Go-Graph': GoGraph,
  'Go-Heart': GoHeart,
  'Go-History': GoHistory,
  'Go-Home': GoHome,
  'Go-HorizontalRule': GoHorizontalRule,
  'Go-Hubot': GoHubot,
  'Go-Inbox': GoInbox,
  'Go-Info': GoInfo,
  'Go-IssueClosed': GoIssueClosed,
  'Go-IssueOpened': GoIssueOpened,
  'Go-IssueReopened': GoIssueReopened,
  'Go-Italic': GoItalic,
  'Go-Jersey': GoJersey,
  'Go-KebabHorizontal': GoKebabHorizontal,
  'Go-KebabVertical': GoKebabVertical,
  'Go-Key': GoKey,
  'Go-Keyboard': GoKeyboard,
  'Go-Law': GoLaw,
  'Go-LightBulb': GoLightBulb,
  'Go-LinkExternal': GoLinkExternal,
  'Go-Link': GoLink,
  'Go-ListOrdered': GoListOrdered,
  'Go-ListUnordered': GoListUnordered,
  'Go-Location': GoLocation,
  'Go-Lock': GoLock,
  'Go-LogoGist': GoLogoGist,
  'Go-LogoGithub': GoLogoGithub,
  'Go-MailRead': GoMailRead,
  'Go-Mail': GoMail,
  'Go-MarkGithub': GoMarkGithub,
  'Go-Markdown': GoMarkdown,
  'Go-Megaphone': GoMegaphone,
  'Go-Mention': GoMention,
  'Go-Milestone': GoMilestone,
  'Go-Mirror': GoMirror,
  'Go-MortarBoard': GoMortarBoard,
  'Go-Mute': GoMute,
  'Go-NoNewline': GoNoNewline,
  'Go-Note': GoNote,
  'Go-Octoface': GoOctoface,
  'Go-Organization': GoOrganization,
  'Go-Package': GoPackage,
  'Go-Paintcan': GoPaintcan,
  'Go-Pencil': GoPencil,
  'Go-Person': GoPerson,
  'Go-Pin': GoPin,
  'Go-Play': GoPlay,
  'Go-Plug': GoPlug,
  'Go-PlusSmall': GoPlusSmall,
  'Go-Plus': GoPlus,
  'Go-PrimitiveDot': GoPrimitiveDot,
  'Go-PrimitiveSquare': GoPrimitiveSquare,
  'Go-Project': GoProject,
  'Go-Pulse': GoPulse,
  'Go-Question': GoQuestion,
  'Go-Quote': GoQuote,
  'Go-RadioTower': GoRadioTower,
  'Go-Reply': GoReply,
  'Go-RepoClone': GoRepoClone,
  'Go-RepoForcePush': GoRepoForcePush,
  'Go-RepoForked': GoRepoForked,
  'Go-RepoPull': GoRepoPull,
  'Go-RepoPush': GoRepoPush,
  'Go-Repo': GoRepo,
  'Go-Report': GoReport,
  'Go-RequestChanges': GoRequestChanges,
  'Go-Rocket': GoRocket,
  'Go-Rss': GoRss,
  'Go-Ruby': GoRuby,
  'Go-ScreenFull': GoScreenFull,
  'Go-ScreenNormal': GoScreenNormal,
  'Go-Search': GoSearch,
  'Go-Server': GoServer,
  'Go-Settings': GoSettings,
  'Go-Shield': GoShield,
  'Go-SignIn': GoSignIn,
  'Go-SignOut': GoSignOut,
  'Go-Smiley': GoSmiley,
  'Go-Squirrel': GoSquirrel,
  'Go-Star': GoStar,
  'Go-Stop': GoStop,
  'Go-Sync': GoSync,
  'Go-Tag': GoTag,
  'Go-Tasklist': GoTasklist,
  'Go-Telescope': GoTelescope,
  'Go-Terminal': GoTerminal,
  'Go-TextSize': GoTextSize,
  'Go-ThreeBars': GoThreeBars,
  'Go-Thumbsdown': GoThumbsdown,
  'Go-Thumbsup': GoThumbsup,
  'Go-Tools': GoTools,
  'Go-Trashcan': GoTrashcan,
  'Go-TriangleDown': GoTriangleDown,
  'Go-TriangleLeft': GoTriangleLeft,
  'Go-TriangleRight': GoTriangleRight,
  'Go-TriangleUp': GoTriangleUp,
  'Go-Unfold': GoUnfold,
  'Go-Unmute': GoUnmute,
  'Go-Unverified': GoUnverified,
  'Go-Verified': GoVerified,
  'Go-Versions': GoVersions,
  'Go-Watch': GoWatch,
  'Go-X': GoX,
  'Go-Zap': GoZap,
};

export interface GithubIconProps {
  name: keyof typeof GithubIconType;
  color?: string;
  size?: number;
  className?: string;
  onClick?: () => void;
}

export const GithubIcon = ({ name, color = '#363636', size = 16, className = '', onClick }: GithubIconProps) => {
  const NinoIcon = GithubIconType[name];

  if (onClick) {
    className += 'clickable';
  }

  return (
    <IconContext.Provider value={{ color: color, size: `${size}px`, className: className }}>
      <NinoIcon onClick={onClick} />
    </IconContext.Provider>
  );
};
