version: 2.1

orbs:
  node: circleci/node@2.0.3

command:
  yarn_install:
    steps:
      - restore_cache:
        name: Restore Dependencies
        keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
        name: Install Dependencies
        command: yarn install
      - save_cache:
        name: Save Dependencies
        key: v1-dependencies-{{ checksum "yarn.lock" }}
        paths:
          - node_modules

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - yarn_install

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - yarn_install
      - run:
        name: Run style lint
        command: yarn lint:style
      - run:
        name: Run Tests
        command: yarn test

  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - yarn_install
      - run:
        name: Build storybook
        command: yarn build-storybook --quiet
      - run:
          name: Netlify Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              curl -X POST -d {} https://api.netlify.com/build_hooks/5ea1ab34446d21ec04ca6eec
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
        requires:
          - build
      - deploy:
        requires:
          - test
        filters:
          branches:
            only: master
